# Generated by Django 3.2.7 on 2021-09-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('batchno', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('weight', models.FloatField()),
                ('processor', models.CharField(max_length=30)),
            ],
        ),
    ]
