# Generated by Django 3.2.7 on 2021-09-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Date',
        ),
    ]
